name: bulma_sass
description: Bulma flexbox CSS framework and its scss components
version: 1.0.0
homepage: https://github.com/indiealexh/dart_bulma_sass
author: Alexander Haslam <alexander.haslam@reincarnadigital.com>

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.2
  git: ^2.0.0
  pub_semver: ^2.1.0
  sass_builder: ^2.1.4
